#!/bin/bash
# fw-adsb-tailnet-bind — publish ADS-B feed ports on the Tailscale IPv4 only.
# Feature: fw-gsd specs/003-usb-adsb-feeder (T012)
#
# Quadlet PublishPort= entries at rest bind 0.0.0.0. For the ADS-B feed ports
# (8080, 8081, 30003, 30005) the spec requires tailnet-only exposure (FR-005):
# this oneshot computes the host's tailscale IPv4 after tailscaled is up and
# writes systemd drop-ins that replace each PublishPort= with a binding to
# that address, then restarts the user quadlets to pick them up.
#
# VERIFY-on-hardware: rootless quadlet restart flow under user@1000; drop-in
# reset semantics (empty PublishPort= resets the list before re-adding).
set -euo pipefail

TS_IP=""
for _ in $(seq 1 30); do
    TS_IP="$(tailscale ip -4 2>/dev/null || true)"
    [ -n "$TS_IP" ] && break
    sleep 2
done

if [ -z "$TS_IP" ]; then
    echo "fw-adsb-tailnet-bind: no tailscale IPv4 after 60s; leaving 0.0.0.0 bindings" >&2
    exit 0
fi

USER_UNIT_DIR=/etc/containers/systemd/users/1000

install -d -m 0755 "${USER_UNIT_DIR}/fw-adsb-readsb.container.d"
cat > "${USER_UNIT_DIR}/fw-adsb-readsb.container.d/20-tailnet-bind.conf" <<EOF
# Auto-generated by fw-adsb-tailnet-bind — do not edit (regenerated on boot).
# Empty PublishPort= first resets the quadlet list, then re-adds tailnet-only
# bindings (systemd list-reset semantics). VERIFY-on-hardware.
[Container]
PublishPort=
PublishPort=${TS_IP}:8080:8080
PublishPort=${TS_IP}:30003:30003
PublishPort=${TS_IP}:30005:30005
EOF

install -d -m 0755 "${USER_UNIT_DIR}/fw-adsb-status.container.d"
cat > "${USER_UNIT_DIR}/fw-adsb-status.container.d/20-tailnet-bind.conf" <<EOF
# Auto-generated by fw-adsb-tailnet-bind — do not edit (regenerated on boot).
[Container]
PublishPort=
PublishPort=${TS_IP}:8081:8081
EOF

# Reload both managers and restart the user quadlets (daemon-reload for the
# user manager requires addressing core's manager; -M core@ needs systemd 257+,
# present on Fedora 45).
systemctl daemon-reload
systemctl -M core@ daemon-reload
systemctl -M core@ restart fw-adsb-readsb.service fw-adsb-status.service || true
