d /var/home/core 0700 core core -
d /var/home/core/.fw-app 0750 core core -
d /var/home/core/.fw-app/data 0750 core core -
d /var/home/core/.fw-app/certs 0700 core core -
d /var/home/core/.fw-app/meta 0750 core core -
d /var/home/core/.config 0700 core core -
d /var/home/core/.config/containers 0700 core core -
d /var/home/core/.config/containers/systemd 0700 core core -
d /var/home/core/.config/containers/systemd/fw-app.container.d 0700 core core -
